### ISSUE TITLE
Feature selection of half runs results in different features selected for the same cells across different treatments

### ISSUE THREAD

**Issue by MikeLippincott** [WayScience/pyroptosis_signature#28]
We need to merge the first and second runs, re-run fs and normalization then we can proceed. I can fork and open a PR for the parquet file merges. Cheers!

**Comment by jenna-tomkinson** [comment]
Interesting! 

Please make sure to perform the merge in the [4.processing_features module for Plate 2](https://github.com/WayScience/pyroptosis_signature/tree/main/Plate_2_data/4.processing_features). In the future, this might be removed if we can use the cluster to rerun the SHSY5Y cells in full.

**Comment by jenna-tomkinson** [comment]
This was completed in PR #29. This issue can be closed now.
